### ISSUE TITLE
Cannot Find Module error while loading the plugin

### ISSUE THREAD

**Issue by shivasairam101** [L13/vscode-diff#1]
Activating extension `L13RARY.l13-diff` failed:  Cannot find module '<<PATH>>/vscode-diff/out/extension.js'

I'm trying to run the plugin after cloning the project. But I'm getting the No module error while activating the plugin. Need help out here.

**Comment by L13** [comment]
Please don't clone this repository. It is just for developing the VS Code Extension. If you want to install the extension, please go to the VS Code Marketplace and you can download it there https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff or you can just easily install it from the VS Code Extension view in the editor itself.
