### ISSUE TITLE
Windows Symbolic Link with path to not existing file ["broken path"]

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#104]
Such are not copied, i use symbolic links also to target dynamically added data, so i hope you implement this support .

Also, Windows 's Hardlinks are unfolded to the whole files, and Junctions converted to Symbolic Links (i do not see these as issues, but maybe there should be a settings or something else) .

**Comment by irvnriir** [comment]
And it feels missed : an ability to copy all, with deleting files with exist only in the targeted folder .

**Comment by irvnriir** [comment]
And, when `l13Diff.abortOnError=false` and the subject symlinks present in 2+/{medium+ amount} of items set to be copied, the copy function seem to run infinitely .

**Comment by L13** [comment]
Hi, I will check it later this week.

**Comment by L13** [comment]
Hi, sorry for the late response. It seems the api does not provide a feature to figure out if it is a hard or a soft link. So I can't fix it.

**Comment by irvnriir** [comment]
As far i understand hardlinks can't be broken . You mean there is no way to determine whether its a symlink or file/folder (the only existing hardlink/ MFT item) ?

Can [this](https://nodejs.org/docs/latest/api/fs.html#fslstatpath-options-callback) help ?

**Comment by irvnriir** [comment]
If { link doesn't work / there is no item at the link's target path } then create such item, make (duplicate) the link, delete the item .

Is there any way to get any output which lets to know that the file is a broken link ?

**Comment by L13** [comment]
This is maybe possible, but I have to test this first. There are two different stat objects in nodejs. Maybe comparing those two does the job.

**Comment by irvnriir** [comment]
`fs.existsSync` fails for such links . the Extension [.zip](https://github.com/L13/vscode-diff/files/8238792/l13rary.l13-diff-1.0.3.zip) repo, contains Commit `#67` which solves the subject (i don't use gulp), but idk whether `if (stat)` will work for not existing file .

**Comment by L13** [comment]
The development for the extension has been paused until autumn, because there is no time to do something. Stuff like this needs a couple of hours and requires min 2 weeks of testing before I release a new version. Sorry for the bad news.

**Comment by irvnriir** [comment]
I would say this specific take less . But i understand you, dw . Meanwhile ones for whom this issue is important, can download and use this zip .

**Comment by L13** [comment]
New release copies now symlinks even if the file in the link does not exist.
