### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nicolassigal** [L13/vscode-diff#108]
- Issue Type: `Performance`
- Extension Name: `l13-diff`
- Extension Version: `0.35.0`
- OS Version: `Darwin x64 20.5.0`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/83/7z4x3g294qs1g88v8kk4brtc0000gr/T/L13RARY.l13-diff-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by L13** [comment]
Hi, the current VS Code version is 1.61 and the extension version is 1.0.3. Maybe you should update first.
