### ISSUE TITLE
Session-based independent filtering configuration

### ISSUE THREAD

**Issue by Flithor** [L13/vscode-diff#109]
feature request as title

**Comment by L13** [comment]
Hi, can you show me an example/workflow please.

**Comment by Flithor** [comment]
![image](https://user-images.githubusercontent.com/23412916/149851524-b2a4194c-ff46-4128-a104-8325dae86230.png)
I would like these settings can be set independently in each compare sission and saved in the history.
Which is now global settings. Global settings can be used as defaults, but are not suitable for all compare. 
Especially "Exclude", currently it can only exclude files or directories that I don't want to compare, but it will be very troublesome if I only want to compare some certain type of files. (because in some comparisons, there may be some file named in UUID without extension name under the directory)

**Comment by L13** [comment]
It is possible to set the configuration per workspace. You can use .vscode/settings.json or the settings config in a *.code-workspace file. The extension looks up for those files and uses the l13Diff.exclude config even if the folder is not part of the current workspace. So you can exclude files per workspace. The other settings are only active if the folder is the current workspace.

see also

https://code.visualstudio.com/docs/getstarted/settings

and

https://code.visualstudio.com/docs/editor/multi-root-workspaces
