### ISSUE TITLE
Please add the feature to compare any 2 arbitrary files in the diff folders tab / diff panel

### ISSUE THREAD

**Issue by anup-das** [L13/vscode-diff#120]
It should be possible to select the file independently using for example Ctrl key from left and right panes and then compare.

Currently i have to leave the diff folders tab and then navigate to explorer and then select the files individually which involving lot of scrolling vertically to find the files from the folders

**Comment by L13** [comment]
Hi, this is still possible. See List Drag'n Drop in the README.

_Drag a path in the list view to another path of the same type (file, folder or symbolic link) and let it drop to open a diff with these two files._

**Comment by anup-das** [comment]
Thanks I did not realize this was possible using drag and drop feature.  I am going to close the issue
