### ISSUE TITLE
Feature Request: Ignore file created/modified timestamps

### ISSUE THREAD

**Issue by rschindhelm-haba** [L13/vscode-diff#121]
I generated a set of files, moved it into a "backup" folder, modified/refactored my applications's code, and regenerated the set of files at a later time. Then I'm trying to compare the set of files generated earlier against the set generated later in order to see if there are any differences in the contents of the file.

Currently, the plugin highlights every file as "modified", because simply their created/modified timestamps differ.

I'd like to suggest adding an option to the plugin settings to ignore file created/modified timestamps (maybe for each option on its own) in order to be able to focus on the contents of the files only.

Here's an example of how it currently looks detects the files as modified, although their contents are identical:
![image](https://user-images.githubusercontent.com/26774899/216632863-4220eed6-3899-474e-8e73-ce767eebaac0.png)

In case the extension does not account file created/modified timestamps, then it might be the case that it picks up on the Byte Order Mark - the left set of files is saved as UTF-8 with BOM, the other as UTF-8 without BOM. In that case, I will place another Feature Request for ignoring the UTF-8 Byte Order Mark when comparing two UTF-8 encoded files.

Can you elaborate?

**Comment by L13** [comment]
Hi, the extension compares always content or if checked only the file size, but never any time or date. If the diff shows a file as modified, there must be something different, because every comparison is by byte.

Please change the review on the marketplace so other users are not confused. Thank you.

The BOM is not ignored right now. This is the reason why the files are shown as modified.

**Comment by rschindhelm-haba** [comment]
Hi, thank you for the feedback. I updated my review on the marketplace.

I'll create a seperate request to ignore the BOM and close this one.
