### ISSUE TITLE
[Feature Request] Semantic Comparison off JSON Files

### ISSUE THREAD

**Issue by davidbitton** [L13/vscode-diff#123]
I'm diffing two folders with JSON files. In one file, the JSON structure is collapsed, and full indent format in the other. Semantically they are the same, not visually. There are several tools for doing the comparison. Is there some sort of hook that allows me to specify a comparator? Thanks!

**Comment by L13** [comment]
Hi, this kind of idea was suggest years ago and I decided it is out of scope. See also https://github.com/L13/vscode-diff/issues/19

**Comment by davidbitton** [comment]
I saw that. i had a need for it today comparing source trees. thanks,
