### ISSUE TITLE
New Feature: Side by side compare

### ISSUE THREAD

**Issue by andergabilondo** [L13/vscode-diff#124]
Great extenssion, congrats!

If i want to use the compare feature of the visual studio to see diff side by side I have to follow the following steps:
1.- Open extenssion
2.- Select "go to file" in the left panel (first folder).
3.- Right click in the file and click "Select for compare".
4.- Select "go to file" in the right panel (second folder).
5.- Right click in the file and click "Compare with selected"

After this I can see both files side by side and changes are highlighted.

Would it be possible to automate this with a button on the side of each file? I think it would make the tool impressive!

Thanks for your support,

Ander

**Comment by L13** [comment]
Hi, you can drag'n drop paths in the list view. See also https://github.com/L13/vscode-diff/issues/120
