### ISSUE TITLE
Folder view file list sorting not case insensitive

### ISSUE THREAD

**Issue by ddncn** [L13/vscode-diff#14]
VS Code version: 1.37.0 (user setup)
Extension version: [0.18.0] - 2019-07-21

I created a vscode-diff-filesTest folder structure, and then compared the folders using this plugin. The screenshot below shows the folder structure and the resulting Folder view in the plugin.

![SortingCaseInsensitive](https://user-images.githubusercontent.com/14152125/62741137-86bf6500-b9ff-11e9-8b48-2b0af292879f.png)

In the screenshot above, I think fileapricot.txt should be sorted above fileButter.txt.

**Comment by L13** [comment]
Hi, good point. I fixed it in version 0.19.0, which will be released tomorrow. Thanks a lot.
