### ISSUE TITLE
git difftool main --dir-diff not working because right are symlinks

### ISSUE THREAD

**Issue by oglops** [L13/vscode-diff#148]
When I `git difftool main --dir-diff` ( If I am on a feature branch) , the right  sub directory files are symlinks pointing to the git repo files, and all files names are dark read,  double clicking on them does not open diff view, no error in output pane.

If I manually set right side pane with git repo directory, the diff works.
The left pane dir are temp files from main branch

**Comment by L13** [comment]
Hi, you need files always "physical" on disk, otherwise a comparison does not work. I don't know if the option --no-symlinks helps. Symlinks are treated as a type. So you can compare only symlinks with symlinks.

**Comment by oglops** [comment]
It works beautifully with `--no-symlinks`, thank you!
