### ISSUE TITLE
[FEATURE REQUEST] Set base folder

### ISSUE THREAD

**Issue by Prodigio** [L13/vscode-diff#152]
I did not see an option to do that, if so, please point me to it. Otherwise my feature request:

I'd love to see an option to set a base folder, which is my main branch, if you like. Additionally a menu button, to compare against said base folder.

Thanks for your useful extension!

**Comment by L13** [comment]
Hi, you can do this with Favorites and Predefined Variables (see README). The variable will be saved in the favorite diff. Now you can compare your current workspace with a specific folder just by click. You can also checkout my other extension "Projects" which supports the diff extension if you have to work with a lot of workspaces. I also recommend to read "Copy files to the left/right folder" which explains how to copy files from one source to multiple destinations at once.
