### ISSUE TITLE
Feature: Ability to normalize text before comparison

### ISSUE THREAD

**Issue by rtiagom** [L13/vscode-diff#157]
I'm using your tool to compare files between two projects that are identical but not the same.  It would be really powerful if I could tell it to ignore certain diffs or normalize the contents for comparison based on a regex replacement logic.

Here's an example:
<img width="1028" alt="Screenshot 2024-06-05 at 6 48 23 PM" src="https://github.com/L13/vscode-diff/assets/54023781/684bf922-5c18-4a0b-b81e-a85a154f3568">

**Comment by L13** [comment]
Hi, the extension just compares folders. The diff viewer is a feature of VS Code. If the extension normalizes the content it would not match the result in the diff viewer which would be confusing. The idea of this extension was always to add just a folder comparison to the diff features of VS Code.

**Comment by rtiagom** [comment]
ok, got it.
