### ISSUE TITLE
"Delete all favourites" command does not delete the default one

### ISSUE THREAD

**Issue by niccolomineo** [L13/vscode-diff#24]
I am trying to delete che default "Diff" favourite, but the "Delete all favourites" command does not work. I am running the latest VScode with the latest vscode-diff version on the latest MacOs X.

**Comment by L13** [comment]
Hi, mmmmh interesting thought. I added this item after I saw a colleague guessing how to open the diff panel. I also thought about removing this item, if a favorite diff exists. Right now it is a feature and not a bug. If somebody is using the extension the first time it is easier to figure out how to open the panel. I think about it.

**Comment by niccolomineo** [comment]
I think saving favourites is an amazing thing to have, so much that it should be a feature on its own.

By default, I imagine I would click on a button saying "Open diff panel" or something like that.

**Comment by niccolomineo** [comment]
I'd also add that the L13 logo (although quite cool!) all over the place confuses me as I thought it would be something I could customise somewhere. So I looked around for a pref option to no avail. 😁

**Comment by L13** [comment]
VS Code does not provide many features for tree views. So I decided to do it this way.

**Comment by niccolomineo** [comment]
I was thinking about something like this (made after the Live Share extension):

<img width="550" alt="Schermata 2019-10-05 alle 00 43 25" src="https://user-images.githubusercontent.com/5409469/66244545-416e9980-e709-11e9-823a-2b144d0fd439.png">
