### ISSUE TITLE
"Open favorite and compare" and "Open to side" do not seem work

### ISSUE THREAD

**Issue by niccolomineo** [L13/vscode-diff#26]
I set them like this but the UI still behaves like in default mode:

<img width="309" alt="Schermata 2019-10-04 alle 17 06 15" src="https://user-images.githubusercontent.com/5409469/66218357-51ff1f80-e6c9-11e9-83f0-258ba7da47ee.png">

**Comment by L13** [comment]
Hi, I have test it and I can't reproduce it. I need more information about VS Code Version, OS, etc.

**Comment by niccolomineo** [comment]
VS Code 1.38.1
OSX Mojave 10.14.6

**Comment by L13** [comment]
I have tested it on different machines with same OS and VS Code version. But I can't reproduce it. Sorry, maybe you have to reinstall the extension or vs code.
