### ISSUE TITLE
Run command after copy

### ISSUE THREAD

**Issue by seeers** [L13/vscode-diff#30]
Hi, 

thanks for this great extension. 

I have already tried to edit and debug the extension in vscode but unfortunately I already failed to set up all development dependencies. Are there any specific requirements for debugging and building the diff extension?

I would like to run a command after successfully copying the selected files to the left or right folder. Ideally with the parameters "left folder" and "right folder".

Thank you.

**Comment by L13** [comment]
Hi, this is a known issue and will be fixed in the next release which will be published this weekend.

Thank you for your interest. Are you planning the feature just for yourself or do you think about a PR? Because right now I do not accept PRs.

**Comment by seeers** [comment]
That sounds good, thank you! First of all for myself but if there is interest I would like to share it.
Background for the feature: I would like to run an automatic git commit in the target directory after copying.

**Comment by L13** [comment]
The new version is online and everything works. Have fun.

**Comment by L13** [comment]
Hi @seeers, I want to give you a short update to the current release. I have refactored a lot, so the source has heavily changed. The good news is, it is now way easier to extend the code with features and it looks and works more like the VS Code API. The class DiffCopy has now an event called "onDidCopyFiles" which will be fired after files have been copied. I think this makes it easier for you.
