### ISSUE TITLE
Wrongly correlated diff

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#36]
![Screenshot 06-05-2020 17 40 53](https://user-images.githubusercontent.com/13949704/83890012-20f15600-a754-11ea-925e-941bbbe694f8.png)

https://mega.nz/folder/MxgWlAqa#n5gF1teZYU_hXwJhPDurKA

**Comment by L13** [comment]
Hi,

sorry, but I have to tell you this is a VS Code issue. My extension compares only folders. If you double click a list entry it opens the two files with the internal VS Code Diff Editor. If you compare the two files in VS Code without my extension you will see the same result. If you need a fix for that problem please open an issue here. https://github.com/Microsoft/vscode/issues

Best regards

**Comment by irvnriir** [comment]
@L13
Another VSC bug X))
