### ISSUE TITLE
Buttons have disappeared

### ISSUE THREAD

**Issue by AmulShah** [L13/vscode-diff#47]
Haven't used diff for a month or so. Tried using it today and all the buttons have disappeared. Could this be related to the new version of Visual Source Code (Version: 1.48.1)?
![Screenshot 2020-08-20 at 21 31 19](https://user-images.githubusercontent.com/4896067/90822526-8523bf00-e32c-11ea-81ce-1946ea8dd3d6.png)

**Comment by AmulShah** [comment]
Perfect thanks. Working now.

**Comment by L13** [comment]
Version 0.29.0 supports the high contrast theme now.
