### ISSUE TITLE
Last Edit date and time

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#54]
showing this in the lists would be useful .

also, this is kind of out of scope, but would be cool to add quick (by edit date + size or/and checksum) checking, and support for comparing large storages (handle: unlimited amount of files, and locked/system/.. files) . so it would be no need to use other software for comparisons in filesystem scope .

**Comment by L13** [comment]
Hi,

> showing this in the lists would be useful .

this feature is on my list but not done yet.

> also, this is kind of out of scope, but would be cool to add quick (by edit date + size or/and checksum) checking,

A way faster comparison is still available if you set

1. "l13Diff.ignoreEndOfLine": false
1. "l13Diff.ignoreTrimWhitespace": "off" OR "l13Diff.ignoreTrimWhitespace": "default" + "diffEditor.ignoreTrimWhitespace": false

> and support for comparing large storages (handle: unlimited amount of files, and locked/system/.. files) . so it would be no need to use other software for comparisons in filesystem scope .

There is not limit implemented right now. If a comparison fails the extension can not access a file or folder or something other strange happens. I do not make any checks. If nodejs send me an error, I stop scanning. The ui has also no limits. The only thing I recognized is the result, which I send from the service to the ui, has a limit. But this is limited by vscode.

**Comment by irvnriir** [comment]
@L13 
not a limit, performance . with a lot of files (compare C:\ to D:\) the interface becomes unresponsive . and yes, i mean the access issues and other, to not break the scan .

**Comment by L13** [comment]
> not a limit, performance . with a lot of files (compare C:\ to D:\), after showing results, the interface becomes unresponsive 

Optimizing the performance of the ui is also on my list but at the end. Main goal right now is to implement all features.

> and yes, i mean the access issues and other -- to not break the scan .

This feature is also on my list but not done yet. The idea is to add a new property "l13Diff.abortOnError" to turn it on or off. I had a similar issue with comparing different file systems. Scanning symlinks on a mac file system with windows doesn't work, but files and folders are working.

My goal is to add all the features on that list this year and to release version 1.0. The extension is a spare time project, so I will not make promises when things will be done.

**Comment by L13** [comment]
Hi, the upcoming release 0.30.0 will include size and date/time for files in the tooltip. I also added the new property "l13Diff.abortOnError". If false the scan process will not stop. The list view includes the new types error and unknown. You can also filter those types in the search widget. I changed the behaviour of the context menu in the list view, so the list view should response faster. The optimization if the list view contains thousands of files will be done later.

**Comment by L13** [comment]
Hi, version 0.30.0 is now available.
