### ISSUE TITLE
Does not work with in-memory file systems

### ISSUE THREAD

**Issue by HoganSlender** [L13/vscode-diff#55]
This is a wonderful plugin, I am a huge fan. I am working on a project that will utilize a in-memory file system (for example https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample). Unfortunately, your plugin doesn't work since the files and directories do not actually reside on disk.

I was wondering if you have thought about switching to using vscode.workspace.fs object instead of node js's fs object? This switch would allow your plugin to work with in-memory file systems. The objects have different methods and properties, but at first glance the functionality to check for file/directory and to open contents is there

I don't know how much of a pain that would be to switch, but thought I would ask.

**Comment by L13** [comment]
Hi and thank you. The reason why I am not using the vscode api is, it does not fully support symbolic links right now. I thought about this, too, but symlinks can't be compared or copied. So I have to remove features. Sorry for the bad news.

**Comment by HoganSlender** [comment]
Makes sense; symlinks are most likely to be more prevalent than in-memory file systems. Thank you for the quick response.
