### ISSUE TITLE
Add setting option to delete file without trash

### ISSUE THREAD

**Issue by MICHAEL-ZENZ** [L13/vscode-diff#64]
Hi, i am currently working on a machine that i cannot change settings(do not have root), and when I try to delete a file it says cannot delete file via trash, provider do not support. So i wonder if it is possible to add a setting option that allows deletion without trash

**Comment by L13** [comment]
Hi, this is possible right now. The extension uses the vscode api and settings to delete files. If you set `files.enableTrash` to false for vscode it will also be disabled for the extension.

**Comment by MICHAEL-ZENZ** [comment]
> Hi, this is possible right now. The extension uses the vscode api and settings to delete files. If you set `files.enableTrash` to false for vscode it will also be disabled for the extension.

Perfect, thank you!
