### ISSUE TITLE
Dates format

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#67]
Please change the dates format to numeral, its much easier to use with operative mental memory (international -- 2020-12-20) .

**Comment by L13** [comment]
Hi, the dates format right now depends on the display language of vscode. Adding other formats means I have to change a lot. I put it on my todo list.

**Comment by L13** [comment]
Hi, the new version is now available and the date format has been changed to 0000-00-00 00:00:00. I removed the previous implementation which depends on the locale language of vscode.
