### ISSUE TITLE
Ignore end of line for text files

### ISSUE THREAD

**Issue by mgsg** [L13/vscode-diff#7]
Hi, thank you for your nice extension. I have been using it for some weeks now. 

I see that the tool is reporting differences between files when one of them uses CRLF and the other one just LF. Is there a simple way to simply ignore this kind of difference?

The diff tool has a key for that:
--strip-trailing-cr

**Comment by mgsg** [comment]
I'm using now an extension called "Line endings" that at least let's me see the differences in terms of CRLF/LF, but it would be nice if files that only differ in that were omitted.

(Sorry for the confusing title of the issue: I was seeing identical files with orange color - they are obviously not identical, but differ only in CRLF/LF chars).

**Comment by L13** [comment]
Hi and thank you for using my extension.

Right now it is not possible to ignore line endings. This feature is since the beginning on my TODO list, but I can not promise when I will do it. Maybe I can develop it earlier as it was planned.

**Comment by L13** [comment]
Hi. The next version will have this feature.

**Comment by L13** [comment]
Version 0.17.0 with ignoring line endings is now available on the VS Code Marketplace. First you have to check the settings and activate this feature. If you open the output channel, you can see how many comparisons have ignored end of line. I hope this makes your tasks easier.
