### ISSUE TITLE
Ignore end of line is not working on all files

### ISSUE THREAD

**Issue by Hax7** [L13/vscode-diff#73]
Enabling end of lines does work on the first folder files but other nested files still shows, I tried to compare the two files and found that one does not have ^M in the end of lines but the other has it on all lines.

**Comment by L13** [comment]
Hi, it seems that the text file detection fails. The detection uses all installed extensions and compares the extname definitions with the file extname. I found a bug in this function if a file starts with `.` or has multiple extnames, for example `.gitignore` or `.js.map`, then the file is not detected as a text file. But if an extname is missing it can be added to `files.associations`.

**Comment by Hax7** [comment]
For me I have .tf(terraform) files and .yml(ansible) files it works great with .tf but the .yml files are still there. maybe this can help you debug it

**Comment by L13** [comment]
VS Code does not support `.yml` by default. You have to install an extension which supports yml like https://marketplace.visualstudio.com/items?itemName=Yseop.vscode-yseopml or you have to add `"*.yml": "text"` to `files.associations` in the settings.

**Comment by Hax7** [comment]
I got it, will try that tomorrow and come back with the results. Thanks

**Comment by L13** [comment]
Hi, I published the new version that fixes the bug I mentioned above. And it seems the other solution also works. So I close the ticket.

**Comment by Hax7** [comment]
I've Installed yaml extension and all is good after. Thanks
