### ISSUE TITLE
"Reveal in Explorer" for Broken -- Symbolic Link

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#82]
It says `file "<<path to the symlink>>" does not exit!` . Explorer Sidebar 's "Reveal in File Explorer" works .

p.s. Using the chance, thanks again, this Extension is incredibly helpful X)

**Comment by L13** [comment]
Hi, and thank you again :)

I have fixed the issue and it will work in the upcoming version. So I close the ticket.
