### ISSUE TITLE
"exclude" in results view

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#88]
Regex has these functions: `((?<!nameToExclude__).*)`, `(((?!nameToExclude__).)*)`; that could be enough, but it doesn't preset currently . It works in VSCode Search 's regex .

**Comment by L13** [comment]
Hi, the regex feature in the search widget does not change anything in the regular expression. If you want to exclude paths in the search view you can use for example `^(?!path/to/ignore|another/path/to/ignore).*$`. For testing regex I use this page https://regex101.com . So you can see if everything works like expected. Do you have an example what kind of paths you want to exclude?

**Comment by irvnriir** [comment]
@L13 with "^" and "$" that'll work, thanks . i guess your script removes/hides results only if the search return "" (and not when it has any difference from subject), that makes part-of-path search codes simpler .

**Comment by L13** [comment]
The code for that is super simple. The regex will be created with the following line

`regexp = new RegExp(useRegExp ? searchterm : escapeForRegExp(searchterm), useCaseSensitive ? '' : 'i');`

and the test will be done with the following line

`fileA && regexp.test(fileA.relative) || fileB && regexp.test(fileB.relative)`

So I don't do any magic between. If the method "test" returns true, the path will be visible. It is just basic JavaScript RegEx. And yes, JavaScript RegEx is sometimes weird ^^

**Comment by irvnriir** [comment]
@L13 its not weird, as i said your/this version makes it easier to find/keep paths with certain part .

i don't use js, but as far i can decode, `regexp.test` is the "==" for "regexp" var and "fileA.relative" .
chesus, the js's "." meaning makes no sense .

**Comment by irvnriir** [comment]
oh, wait . so you negate/reverse the check's output ?

**Comment by irvnriir** [comment]
don't see `==` shortcuts in JS Regex, so the version for my codes would be like `regexp.source` and then "==" some thing .? doesn't matter anyway, the subject works as is .
