### ISSUE TITLE
List moves on Copy

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#93]
Scroll some, use Copy on file . The scrolling will jump to top .

**Comment by L13** [comment]
Hi, I found the reason for the issue and fixed it. I have to do some QA until I publish the bugfix, because I had to change some important parts. Planned release date is Sunday if everything works like expected.

**Comment by L13** [comment]
I have published version 1.0.1 with the fix. If you copy, delete or change a file, the list view keeps the position. So I close the ticket.
